/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventState = IDL.Variant({
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'past' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const EventCategory = IDL.Variant({
  'bar' : IDL.Null,
  'concert' : IDL.Null,
  'other' : IDL.Null,
  'dining' : IDL.Null,
  'party' : IDL.Null,
  'sports' : IDL.Null,
});
export const EventView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'state' : EventState,
  'timestamp' : IDL.Int,
  'attendees' : IDL.Vec(IDL.Principal),
  'category' : EventCategory,
  'location' : IDL.Text,
});
export const PersistentGroupView = IDL.Record({
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const UserProfileView = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'preferredCategories' : IDL.Vec(EventCategory),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'areFriends' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([EventView], [IDL.Nat], []),
  'createGroup' : IDL.Func([PersistentGroupView], [IDL.Nat], []),
  'getAllGroups' : IDL.Func([], [IDL.Vec(PersistentGroupView)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventAttendees' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEventCategories' : IDL.Func([], [IDL.Vec(EventCategory)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
  'getEventsAttending' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EventView)],
      ['query'],
    ),
  'getEventsByCategory' : IDL.Func(
      [EventCategory],
      [IDL.Vec(EventView)],
      ['query'],
    ),
  'getEventsCreated' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EventView)],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFriendsOfUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(PersistentGroupView)], ['query']),
  'getGroupMembers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getIncomingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
  'getUserGroups' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isAgeVerified' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserAgeVerified' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Nat], [], []),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'rsvpEvent' : IDL.Func([IDL.Nat, IDL.Bool], [EventView], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventState = IDL.Variant({
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'past' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const EventCategory = IDL.Variant({
    'bar' : IDL.Null,
    'concert' : IDL.Null,
    'other' : IDL.Null,
    'dining' : IDL.Null,
    'party' : IDL.Null,
    'sports' : IDL.Null,
  });
  const EventView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'state' : EventState,
    'timestamp' : IDL.Int,
    'attendees' : IDL.Vec(IDL.Principal),
    'category' : EventCategory,
    'location' : IDL.Text,
  });
  const PersistentGroupView = IDL.Record({
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserProfileView = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'preferredCategories' : IDL.Vec(EventCategory),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'areFriends' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([EventView], [IDL.Nat], []),
    'createGroup' : IDL.Func([PersistentGroupView], [IDL.Nat], []),
    'getAllGroups' : IDL.Func([], [IDL.Vec(PersistentGroupView)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventAttendees' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEventCategories' : IDL.Func([], [IDL.Vec(EventCategory)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
    'getEventsAttending' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EventView)],
        ['query'],
      ),
    'getEventsByCategory' : IDL.Func(
        [EventCategory],
        [IDL.Vec(EventView)],
        ['query'],
      ),
    'getEventsCreated' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EventView)],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFriendsOfUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(PersistentGroupView)], ['query']),
    'getGroupMembers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getIncomingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
    'getUserGroups' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isAgeVerified' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserAgeVerified' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Nat], [], []),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'rsvpEvent' : IDL.Func([IDL.Nat, IDL.Bool], [EventView], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };