/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EventCategory = { 'bar' : null } |
  { 'concert' : null } |
  { 'other' : null } |
  { 'dining' : null } |
  { 'party' : null } |
  { 'sports' : null };
export type EventState = { 'upcoming' : null } |
  { 'cancelled' : null } |
  { 'past' : null } |
  { 'ongoing' : null };
export interface EventView {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'maxAttendees' : [] | [bigint],
  'createdAt' : bigint,
  'description' : string,
  'state' : EventState,
  'timestamp' : bigint,
  'attendees' : Array<Principal>,
  'category' : EventCategory,
  'location' : string,
}
export interface PersistentGroupView {
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface UserProfileView {
  'age' : bigint,
  'bio' : string,
  'username' : string,
  'preferredCategories' : Array<EventCategory>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'areFriends' : ActorMethod<[Principal, Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[EventView], bigint>,
  'createGroup' : ActorMethod<[PersistentGroupView], bigint>,
  'getAllGroups' : ActorMethod<[], Array<PersistentGroupView>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventAttendees' : ActorMethod<[bigint], Array<Principal>>,
  'getEventCategories' : ActorMethod<[], Array<EventCategory>>,
  'getEvents' : ActorMethod<[], Array<EventView>>,
  'getEventsAttending' : ActorMethod<[Principal], Array<EventView>>,
  'getEventsByCategory' : ActorMethod<[EventCategory], Array<EventView>>,
  'getEventsCreated' : ActorMethod<[Principal], Array<EventView>>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getFriendsOfUser' : ActorMethod<[Principal], Array<Principal>>,
  'getGroup' : ActorMethod<[bigint], [] | [PersistentGroupView]>,
  'getGroupMembers' : ActorMethod<[bigint], Array<Principal>>,
  'getIncomingFriendRequests' : ActorMethod<[], Array<Principal>>,
  'getUpcomingEvents' : ActorMethod<[], Array<EventView>>,
  'getUserGroups' : ActorMethod<[Principal], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isAgeVerified' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserAgeVerified' : ActorMethod<[Principal], boolean>,
  'joinGroup' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'rejectFriendRequest' : ActorMethod<[Principal], undefined>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'rsvpEvent' : ActorMethod<[bigint, boolean], EventView>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];