/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfileView {
    age: bigint;
    bio: string;
    username: string;
    preferredCategories: Array<EventCategory>;
}
export interface EventView {
    id: bigint;
    title: string;
    creator: Principal;
    maxAttendees?: bigint;
    createdAt: bigint;
    description: string;
    state: EventState;
    timestamp: bigint;
    attendees: Array<Principal>;
    category: EventCategory;
    location: string;
}
export interface PersistentGroupView {
    creator: Principal;
    members: Array<Principal>;
    name: string;
    createdAt: bigint;
    description: string;
}
export enum EventCategory {
    bar = "bar",
    concert = "concert",
    other = "other",
    dining = "dining",
    party = "party",
    sports = "sports"
}
export enum EventState {
    upcoming = "upcoming",
    cancelled = "cancelled",
    past = "past",
    ongoing = "ongoing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(fromUser: Principal): Promise<void>;
    areFriends(user1: Principal, user2: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(input: EventView): Promise<bigint>;
    createGroup(group: PersistentGroupView): Promise<bigint>;
    getAllGroups(): Promise<Array<PersistentGroupView>>;
    getAllUserProfiles(): Promise<Array<UserProfileView>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEventAttendees(eventId: bigint): Promise<Array<Principal>>;
    getEventCategories(): Promise<Array<EventCategory>>;
    getEvents(): Promise<Array<EventView>>;
    getEventsAttending(user: Principal): Promise<Array<EventView>>;
    getEventsByCategory(category: EventCategory): Promise<Array<EventView>>;
    getEventsCreated(user: Principal): Promise<Array<EventView>>;
    getFriends(): Promise<Array<Principal>>;
    getFriendsOfUser(user: Principal): Promise<Array<Principal>>;
    getGroup(groupId: bigint): Promise<PersistentGroupView | null>;
    getGroupMembers(groupId: bigint): Promise<Array<Principal>>;
    getIncomingFriendRequests(): Promise<Array<Principal>>;
    getUpcomingEvents(): Promise<Array<EventView>>;
    getUserGroups(user: Principal): Promise<Array<bigint>>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    isAgeVerified(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isUserAgeVerified(user: Principal): Promise<boolean>;
    joinGroup(groupId: bigint): Promise<void>;
    leaveGroup(groupId: bigint): Promise<void>;
    rejectFriendRequest(fromUser: Principal): Promise<void>;
    removeFriend(friend: Principal): Promise<void>;
    rsvpEvent(id: bigint, join: boolean): Promise<EventView>;
    saveCallerUserProfile(profile: UserProfileView): Promise<void>;
    sendFriendRequest(toUser: Principal): Promise<void>;
}
import type { EventCategory as _EventCategory, EventState as _EventState, EventView as _EventView, PersistentGroupView as _PersistentGroupView, UserProfileView as _UserProfileView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async areFriends(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.areFriends(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.areFriends(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: EventView): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_EventView_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_EventView_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGroup(arg0: PersistentGroupView): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async getAllGroups(): Promise<Array<PersistentGroupView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventAttendees(arg0: bigint): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventAttendees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventAttendees(arg0);
            return result;
        }
    }
    async getEventCategories(): Promise<Array<EventCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventCategories();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventCategories();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsAttending(arg0: Principal): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsAttending(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsAttending(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByCategory(arg0: EventCategory): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByCategory(to_candid_EventCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByCategory(to_candid_EventCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsCreated(arg0: Principal): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsCreated(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsCreated(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getFriendsOfUser(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsOfUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsOfUser(arg0);
            return result;
        }
    }
    async getGroup(arg0: bigint): Promise<PersistentGroupView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMembers(arg0: bigint): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return result;
        }
    }
    async getIncomingFriendRequests(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingFriendRequests();
            return result;
        }
    }
    async getUpcomingEvents(): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserGroups(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGroups(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGroups(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAgeVerified(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAgeVerified();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAgeVerified();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserAgeVerified(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserAgeVerified(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserAgeVerified(arg0);
            return result;
        }
    }
    async joinGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async rejectFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async rsvpEvent(arg0: bigint, arg1: boolean): Promise<EventView> {
        if (this.processError) {
            try {
                const result = await this.actor.rsvpEvent(arg0, arg1);
                return from_candid_EventView_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rsvpEvent(arg0, arg1);
            return from_candid_EventView_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
}
function from_candid_EventCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EventState_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventState): EventState {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EventView_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventView): EventView {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentGroupView]): PersistentGroupView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    username: string;
    preferredCategories: Array<_EventCategory>;
}): {
    age: bigint;
    bio: string;
    username: string;
    preferredCategories: Array<EventCategory>;
} {
    return {
        age: value.age,
        bio: value.bio,
        username: value.username,
        preferredCategories: from_candid_vec_n12(_uploadFile, _downloadFile, value.preferredCategories)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    maxAttendees: [] | [bigint];
    createdAt: bigint;
    description: string;
    state: _EventState;
    timestamp: bigint;
    attendees: Array<Principal>;
    category: _EventCategory;
    location: string;
}): {
    id: bigint;
    title: string;
    creator: Principal;
    maxAttendees?: bigint;
    createdAt: bigint;
    description: string;
    state: EventState;
    timestamp: bigint;
    attendees: Array<Principal>;
    category: EventCategory;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        maxAttendees: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.maxAttendees)),
        createdAt: value.createdAt,
        description: value.description,
        state: from_candid_EventState_n22(_uploadFile, _downloadFile, value.state),
        timestamp: value.timestamp,
        attendees: value.attendees,
        category: from_candid_EventCategory_n13(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    concert: null;
} | {
    other: null;
} | {
    dining: null;
} | {
    party: null;
} | {
    sports: null;
}): EventCategory {
    return "bar" in value ? EventCategory.bar : "concert" in value ? EventCategory.concert : "other" in value ? EventCategory.other : "dining" in value ? EventCategory.dining : "party" in value ? EventCategory.party : "sports" in value ? EventCategory.sports : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    cancelled: null;
} | {
    past: null;
} | {
    ongoing: null;
}): EventState {
    return "upcoming" in value ? EventState.upcoming : "cancelled" in value ? EventState.cancelled : "past" in value ? EventState.past : "ongoing" in value ? EventState.ongoing : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventCategory>): Array<EventCategory> {
    return value.map((x)=>from_candid_EventCategory_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventView>): Array<EventView> {
    return value.map((x)=>from_candid_EventView_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileView>): Array<UserProfileView> {
    return value.map((x)=>from_candid_UserProfileView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_EventCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EventState_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventState): _EventState {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_EventView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventView): _EventView {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileView): _UserProfileView {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    username: string;
    preferredCategories: Array<EventCategory>;
}): {
    age: bigint;
    bio: string;
    username: string;
    preferredCategories: Array<_EventCategory>;
} {
    return {
        age: value.age,
        bio: value.bio,
        username: value.username,
        preferredCategories: to_candid_vec_n27(_uploadFile, _downloadFile, value.preferredCategories)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    maxAttendees?: bigint;
    createdAt: bigint;
    description: string;
    state: EventState;
    timestamp: bigint;
    attendees: Array<Principal>;
    category: EventCategory;
    location: string;
}): {
    id: bigint;
    title: string;
    creator: Principal;
    maxAttendees: [] | [bigint];
    createdAt: bigint;
    description: string;
    state: _EventState;
    timestamp: bigint;
    attendees: Array<Principal>;
    category: _EventCategory;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        maxAttendees: value.maxAttendees ? candid_some(value.maxAttendees) : candid_none(),
        createdAt: value.createdAt,
        description: value.description,
        state: to_candid_EventState_n5(_uploadFile, _downloadFile, value.state),
        timestamp: value.timestamp,
        attendees: value.attendees,
        category: to_candid_EventCategory_n7(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventState): {
    upcoming: null;
} | {
    cancelled: null;
} | {
    past: null;
} | {
    ongoing: null;
} {
    return value == EventState.upcoming ? {
        upcoming: null
    } : value == EventState.cancelled ? {
        cancelled: null
    } : value == EventState.past ? {
        past: null
    } : value == EventState.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    bar: null;
} | {
    concert: null;
} | {
    other: null;
} | {
    dining: null;
} | {
    party: null;
} | {
    sports: null;
} {
    return value == EventCategory.bar ? {
        bar: null
    } : value == EventCategory.concert ? {
        concert: null
    } : value == EventCategory.other ? {
        other: null
    } : value == EventCategory.dining ? {
        dining: null
    } : value == EventCategory.party ? {
        party: null
    } : value == EventCategory.sports ? {
        sports: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EventCategory>): Array<_EventCategory> {
    return value.map((x)=>to_candid_EventCategory_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
